version: '3'

volumes:
  mysql:
    driver: local
  solr:
    driver: local
  fcrepo:
    driver: local
  redis:
    driver: local

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - mysql:/var/lib/mysql

  solr:
    image: murny/docker-solr-legacy:5.4
    # Uncomment this if you want to access SOLR's web interface
    # ports:
    #   - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
      - ./solr_conf/conf:/config
      - ./solr_conf/scripts/solr-precreate-hydranorth.sh:/docker-entrypoint-initdb.d/solr-precreate-hydranorth.sh


  fcrepo:
    image: murny/docker-fcrepo4:4.2
    volumes:
      - fcrepo:/fcrepo4-data
    # Uncomment this if you want to access Fedora's web interface
    # ports:
    #   - "8080:8080"

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  web:
    build: .
    image: ualbertalib/hydranorth
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b "0.0.0.0"'
    environment:
      RAILS_ENV: development
      # EZID_PASSWORD: uncomment and add this if you want DOIs
      DATABASE_URL: 'mysql2://:mysecretpassword@mysql/'
      FCREPO_URL: http://fcrepo:8080/fcrepo/rest
      SOLR_URL: http://solr:8983/solr/development
      SOLR_TEST_URL: http://solr:8983/solr/test
      REDIS_URL: 'redis://redis/1'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - fcrepo
      - redis
      - solr

  worker:
    build: .
    image: ualbertalib/hydranorth
    command: bundle exec rake environment resque:work QUEUE=*
    environment:
      RAILS_ENV: development
      # EZID_PASSWORD: uncomment and add this if you want DOIs
      DATABASE_URL: 'mysql2://:mysecretpassword@mysql/'
      FCREPO_URL: http://fcrepo:8080/fcrepo/rest
      SOLR_URL: http://solr:8983/solr/development
      SOLR_TEST_URL: http://solr:8983/solr/test
      REDIS_URL: 'redis://redis/1'
    volumes:
      - .:/app
    depends_on:
      - mysql
      - fcrepo
      - redis
      - solr
